CREATE TABLE nelson_pediatrics (
    id BIGSERIAL PRIMARY KEY,
    chapter_number TEXT,
    chapter_title TEXT,
    section_title TEXT,
    subsection_title TEXT,
    topic_title TEXT,
    background TEXT,
    epidemiology TEXT,
    pathophysiology TEXT,
    clinical_presentation TEXT,
    diagnostics TEXT,
    differential_diagnoses TEXT,
    management TEXT,
    prevention TEXT,
    notes TEXT,
    drug_name TEXT,
    drug_indication TEXT,
    drug_mechanism TEXT,
    drug_adverse_effects TEXT,
    drug_contraindications TEXT,
    dosage_age_group TEXT,
    dosage_route TEXT,
    dosage_value TEXT,
    dosage_max TEXT,
    dosage_frequency TEXT,
    dosage_special_considerations TEXT,
    procedure_name TEXT,
    procedure_steps TEXT,
    procedure_complications TEXT,
    procedure_equipment TEXT,
    algorithm_title TEXT,
    algorithm_description TEXT,
    algorithm_flowchart_url TEXT,
    reference_citation TEXT,
    reference_doi TEXT,
    reference_url TEXT,
    media_url TEXT,
    media_type TEXT,
    media_caption TEXT,
    revised_by TEXT,
    revision_notes TEXT,
    revision_date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);